### PR TITLE
cosmetics update for VC2015

### PR DESCRIPTION
**Pull request by crocsg**
Hello,
i tried to use ofxMQTT on Win10 with VC2015 and there where few compilation errors. I correct them (mostly explicit cast) with minimal change. Maybe the biggest thing is defining _CRT_SECURE_NO_WARNINGS in config.h.

### CODE REVIEW

**Comment by 256dpi** [comment]
Thanks a lot for your work! Unfortunately, the mosquitto library is pulled in as an external dependency and will be updated in the future. This will remove your changes immediately. See here https://github.com/256dpi/ofxMQTT/blob/master/update.sh.

I would recommend to initiate a discussion about the changes on the upstream repository: https://github.com/eclipse/mosquitto.

**Comment by crocsg** [comment]
Hello,
i've just tested the mosquitto last release (https://github.com/eclipse/mosquitto) and it compile like a breeze under Windows with VC2015. May i suggest you to update the mosquitto files in a branch, so you can test it under Mac and i can test it under Windows. If it works the openframework community will gain a full portable MQTT addons.

**Comment by 256dpi** [comment]
Here we go: https://github.com/256dpi/ofxMQTT/pull/8.

Can you test that on Windows?

**Comment by crocsg** [comment]
Hello,

i've done some tests, and i have a working version under VC2015 with of 9.8

The bad news is that nearly  all the compilation problems under windows come from the OpenFramework project generator.

- Compilation forced to CPP even for C file result in all the cast conversion errors.

- Compilation forced to unicode, as original mosquitto project use multi-bytes (just another historical windows mess)

- The original files of mosquitto are embedded in the addon, but mosquitto files are design to build library, this result in some specifics errors due to the windows dynamic library handling.

Obviously the mosquitto project is very well done with cmake, can be use as is in production project.  I'm not inclined to put some mess in it to have a good OpenFrameworks addons.


I think the situation offer 3 solutions :

1) I need some time, but may be all the compilation problems can be solved with tricky compilation options under Visual C. This will imply a good documentation for Windows user of the addons, this will maybe difficult for beginners, and need to be done in each project using ofxMQTT.

2) As i've start to do, we modify the mosquitto source in a minimal manner to have it compile under windows. This imply to upgrade the code whenever you upgrade the mosquitto files in the addons, but it seem you don't do this often.

3) Build a specific Windows MQTT addons


On my opinion the solution 2 is the better one, from a beginner (or a non professional windows C++ coder)  point of view.  As you are the original creator of the addons i'm wondering what's your preferred option ?

**Comment by 256dpi** [comment]
That's very unfortunate. Is there no way to teach OF to compile the c files correctly? Since mosquitto is  widely used on windows I assume it must work without a lot of errors?

@fabianmoronzirfas Do you have an idea here?

**Comment by crocsg** [comment]
Has i said the c++ compilation is forced by the Of project generation tool, maybe for some good reasons, But with some cast and little modifications mosquitto files can be compiled in c++ and work well.

**Comment by ff6347** [comment]
@256dpi sorry no idea about that. I recently had on a different project compilation errors in XCode that only where warnings when using make. 

Could the changes for windows be done with some kind of overwrite that is part of the addon? Or could these changes be automated into a step of the update script?

**Comment by ff6347** [comment]
Also. If the problems come from the projectGenerator I would suggest first reporting that to the OF team rather then do some fixes that are only for the code created from the generator.

**Comment by crocsg** [comment]
It seems wea ra not talking about the real problem :-), we are going very technical.

At this time the ofxMQTT addon compile with errors under Windows Visual C++ (2015 and 2017), so nobody can use it under windows without modifications (that was my problem at start).

The code modification to have the addons compile under Windows is just some explicit cast like this
message = _mosquitto_calloc(1, sizeof(struct mosquitto_message_all));
modified in
message = (mosquitto_message_all*) _mosquitto_calloc(1, sizeof(struct mosquitto_message_all));

Just because VC2015 consider it is an error to implicit cast a void* into a mosquitto_message_all*

with this kind of modifications, we are pretty sure that the source file compile under Mac, Linux and Windows.

After thinking a little bit more, i would prefer to modify the ofxMQTT addons rather than modifiy the OF plugins. Because we can test ofxMQTT and because mixing C and C++ compiler in the same project is not as simple as that for non specialist coder. I'm pretty sure that OF project generator force C++ compiler on all platforms (MAC, Linux, Windows)

At last, i would suggest to modify the mosquitto files (i will do it) to have a simple addons that beginners can add in their projects and have it working without thinking about the tricky diff beween C and C++ compiler

**Comment by 256dpi** [comment]
I'm closing this as there is nothing we can do here.

**Pull request closed without merging**
